title: Migrating your repository to GitHub
description: You're a migration away from using a full suite of development tools and premier third-party apps on GitHub. This course helps you seamlessly move code to GitHub and sets you up to do more after you make the move.
template:
  name: github-move
  repo: false
before:
  - type: createIssue
    title: Plan the move
    body: 01_make-a-plan.md
steps:
  - title: Plan the migration
    description: Explore your options for making the move to GitHub
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: createIssue
        action_id: new_issue
        title: Preparing the project for Git
        body: 04_prepare.md
      - type: respond
        with: 02_next.md
        data:
          issueURL: '%actions.new_issue.data.html_url%'

  - title: Prepare the project
    description: Get your project ready to be moved to GitHub
    event: issues.closed
    link: '{{ repoUrl }}/issues'
    actions:
      - type: createIssue
        action_id: new_issue
        title: Public or private repository?
        body: 07_confirm-visibility.md
        data:
          private: '%payload.repository.private%'
      - type: respond
        with: 02_next.md
        data:
          issueURL: '%actions.new_issue.data.html_url%'

  - title: Public or private repository?
    description: Understand the difference between a public and private repository
    event: issues.closed
    link: '{{ repoUrl }}/issues'
    actions:
      - type: createIssue
        title: Importing your project
        body: 05_move-import.md
        comments:
          - 08_graceful-exit.md
        action_id: new_issue
      - type: respond
        with: 02_next.md
        data:
          issueURL: '%actions.new_issue.data.html_url%'

  - title: Complete the Import
    description: Publish your project on GitHub
    event: push
    link: '{{ repoUrl }}/issues'
    actions:
      - type: closeIssue
        issue: Importing your project
        action_id: closed

tags: [
  'Git','GitHub'
]
